### ISSUE TITLE
Problem with label .csv file

### ISSUE THREAD

**Issue by stachu86** [MSP-UTD/MSP-Podcast_Challenge#1]
What should be in `processed_labels.csv` or what should I put in config as `label_path`? This file is not provided in the dataset. When I tried to use `labels_consensus.csv` I got :
```python
Traceback (most recent call last):
  File "/mnt/w01/user/github/MSP-Podcast_Challenge/train_ft_cat_ser_weighted.py", line 76, in <module>
    class_frequencies = train_df[classes].sum().to_dict()
  File "/home/user/micromamba/envs/msp/lib/python3.9/site-packages/pandas/core/frame.py", line 3902, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/user/micromamba/envs/msp/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6114, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/user/micromamba/envs/msp/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6175, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Angry', 'Sad', 'Happy', 'Surprise', 'Fear', 'Disgust', 'Contempt',\n       'Neutral'],\n      dtype='object')] are in the [columns]"
```

**Comment by ilucasgoncalves** [comment]
Thank you for reaching out about this issue. I have updated the `README` file to explain how to run the model for categorical emotion recognition. Additionally, I added code to properly process the `label_consensus.csv` file for categorical emotion recognition.

See bellow brief explanation:

Configuration

Categorical Emotion Recognition Model

Before running training or evaluation of categorical emotion recognition model. Please execute the script `process_labels_for_categorical.py` to properly format the provided l`abels_consensus.csv` file for categorical emotion recognition. Then place the path of the processed .csv file in the config.json file to run this configuration.
